In [372]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import random
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier
from sklearn import svm
from sklearn.neighbors import KNeighborsClassifier
from sklearn import tree

In [373]:
data_frame = pd.read_csv("Maternal Health Risk Data Set.csv")
data_frame

Age  SystolicBP  DiastolicBP    BS  BodyTemp  HeartRate  RiskLevel
0      25         130           80  15.0      98.0         86  high risk
1      35         140           90  13.0      98.0         70  high risk
2      29          90           70   8.0     100.0         80  high risk
3      30         140           85   7.0      98.0         70  high risk
4      35         120           60   6.1      98.0         76   low risk
...   ...         ...          ...   ...       ...        ...        ...
1009   22         120           60  15.0      98.0         80  high risk
1010   55         120           90  18.0      98.0         60  high risk
1011   35          85           60  19.0      98.0         86  high risk
1012   43         120           90  18.0      98.0         70  high risk
1013   32         120           65   6.0     101.0         76   mid risk

[1014 rows x 7 columns]

In [374]:
new_data_frame = data_frame.iloc[:,[0,1,2,3,4,5]]
new_data_frame

Age  SystolicBP  DiastolicBP    BS  BodyTemp  HeartRate
0      25         130           80  15.0      98.0         86
1      35         140           90  13.0      98.0         70
2      29          90           70   8.0     100.0         80
3      30         140           85   7.0      98.0         70
4      35         120           60   6.1      98.0         76
...   ...         ...          ...   ...       ...        ...
1009   22         120           60  15.0      98.0         80
1010   55         120           90  18.0      98.0         60
1011   35          85           60  19.0      98.0         86
1012   43         120           90  18.0      98.0         70
1013   32         120           65   6.0     101.0         76

[1014 rows x 6 columns]

In [376]:
for i in range(len(data_frame.iloc[:,6])):
    if data_frame.iloc[:,6][i] == 'low risk':
        data_frame.iloc[:,6][i] = 0
        
    elif data_frame.iloc[:,6][i] == 'mid risk':
        data_frame.iloc[:,6][i] = 1 
        
    elif data_frame.iloc[:,6][i] == 'high risk':
        data_frame.iloc[:,6][i] = 2

In [378]:
y_test =sorted(random.sample(range(0, 1015), int(0.3*1014)))

In [379]:
y_train = []
for i in range(len(data_frame)):
    if i not in y_test:
        y_train.append(i)
y_train = sorted(y_train)

In [380]:
x_train = data_frame.iloc[y_train, [0,1,2,3,4,5]]
x_train

Age  SystolicBP  DiastolicBP     BS  BodyTemp  HeartRate
1      35         140           90  13.00      98.0         70
2      29          90           70   8.00     100.0         80
3      30         140           85   7.00      98.0         70
4      35         120           60   6.10      98.0         76
5      23         140           80   7.01      98.0         70
...   ...         ...          ...    ...       ...        ...
1007   40         120           75   7.70      98.0         70
1008   48         120           80  11.00      98.0         88
1010   55         120           90  18.00      98.0         60
1012   43         120           90  18.00      98.0         70
1013   32         120           65   6.00     101.0         76

[710 rows x 6 columns]

In [381]:
y_train = data_frame.iloc[y_train, 6]
y_train = y_train.astype(int)
y_train

1       2
2       2
3       2
4       0
5       2
       ..
1007    2
1008    2
1010    2
1012    2
1013    1
Name: RiskLevel, Length: 710, dtype: int32

In [382]:
x_test = data_frame.iloc[y_test ,[0,1,2,3,4,5]]
x_test

Age  SystolicBP  DiastolicBP    BS  BodyTemp  HeartRate
0      25         130           80  15.0      98.0         86
8      32         120           90   6.9      98.0         70
19     10          70           50   6.9      98.0         70
20     40         140          100  18.0      98.0         90
24     21         120           80   7.5      98.0         76
...   ...         ...          ...   ...       ...        ...
1000   12          90           60  11.0     102.0         60
1003   50         130          100  16.0      98.0         76
1005   17          90           65   7.7     103.0         67
1009   22         120           60  15.0      98.0         80
1011   35          85           60  19.0      98.0         86

[304 rows x 6 columns]

In [383]:
y_test =  data_frame.iloc[y_test ,6]
y_test =  y_test.astype(int)
y_test

0       2
8       1
19      0
20      2
24      0
       ..
1000    2
1003    2
1005    2
1009    2
1011    2
Name: RiskLevel, Length: 304, dtype: int32

In [401]:
model = tree.DecisionTreeClassifier(criterion= "entropy", max_depth = 20 ,min_samples_split = 2,min_samples_leaf = 1 , max_features = "sqrt")
train_model = model.fit(x_train, list(y_train.to_numpy()))
p_train = train_model.predict(list(x_train.to_numpy()))
p_test = train_model.predict(list(x_test.to_numpy()))
accuracy_test = sum(p_test == (y_test).to_numpy())/304*100
accuracy_train = sum(p_train == list(y_train.to_numpy()))/710*100
print("accuracy_test:" , accuracy_test, "\n"+"accuracy_train: " , accuracy_train)

accuracy_test: 81.9078947368421 
accuracy_train:  92.95774647887323


In [448]:
s = cross_val_score(model, x_train, y_train , cv = 6)
c = np.mean(s)
print("cross val score: %" , c*100)

cross val score: % 80.40521293263069


In [449]:
m = confusion_matrix(y_test, p_test)
print(m)

[[96 25  2]
 [19 68 10]
 [ 3  6 75]]


In [465]:
model = tree.DecisionTreeClassifier(criterion= "entropy" , max_depth = 19 , min_samples_leaf = 1 , max_features = "auto")
train_model = model.fit(x_train, list(y_train.to_numpy()))
p_train = train_model.predict(list(x_train.to_numpy()))
p_test = train_model.predict(list(x_test.to_numpy()))
accuracy_test = sum(p_test == (y_test).to_numpy())/304*100
accuracy_train = sum(p_train == list(y_train.to_numpy()))/710*100
print("accuracy_test:" , accuracy_test, "\n"+"accuracy_train: " , accuracy_train)

accuracy_test: 80.5921052631579 
accuracy_train:  92.95774647887323


In [467]:
s = cross_val_score(model, x_train, y_train , cv = 5)
c = np.mean(s)
print("cross val score: %" , c*100)

cross val score: % 81.26760563380282


In [468]:
m = confusion_matrix(y_test, p_test)
print(m)

[[94 24  5]
 [15 74  8]
 [ 2  5 77]]


In [479]:
model = tree.DecisionTreeClassifier(max_depth = 25 , min_samples_leaf = 1 , max_features = "log2")
train_model = model.fit(x_train, list(y_train.to_numpy()))
p_train = train_model.predict(list(x_train.to_numpy()))
p_test = train_model.predict(list(x_test.to_numpy()))
accuracy_test = sum(p_test == (y_test).to_numpy())/304*100
accuracy_train = sum(p_train == list(y_train.to_numpy()))/710*100
print("accuracy_test:" , accuracy_test, "\n"+"accuracy_train: " , accuracy_train)

accuracy_test: 75.6578947368421 
accuracy_train:  92.95774647887323


In [482]:
s = cross_val_score(model, x_train, y_train , cv = 5)
c = np.mean(s)
print("cross val score: %" , c*100)

cross val score: % 78.87323943661973


In [483]:
m = confusion_matrix(y_test, p_test)
print(m)

[[87 31  5]
 [15 72 10]
 [ 6  7 71]]


# KNN

In [540]:
model = KNeighborsClassifier(n_neighbors=3, weights='distance', leaf_size=20 , p=1)
train_model = model.fit(x_train, list(y_train.to_numpy()))
p_train = train_model.predict(list(x_train.to_numpy()))
p_test = train_model.predict(list(x_test.to_numpy()))
accuracy_test = sum(p_test == (y_test).to_numpy())/304*100
accuracy_train = sum(p_train == list(y_train.to_numpy()))/710*100
print("accuracy_test:" , accuracy_test, "\n"+"accuracy_train: " , accuracy_train)

accuracy_test: 78.28947368421053 
accuracy_train:  92.95774647887323


In [547]:
s = cross_val_score(model, x_train, y_train , cv = 8)
c = np.mean(s)
print("cross val score: %" , c*100)

cross val score: % 80.69458631256383


In [548]:
m = confusion_matrix(y_test, p_test)
print(m)

[[98 21  4]
 [19 70  8]
 [ 7  7 70]]


In [554]:
model = KNeighborsClassifier(n_neighbors=10, weights='distance', leaf_size=2 )
train_model = model.fit(x_train, list(y_train.to_numpy()))
p_train = train_model.predict(list(x_train.to_numpy()))
p_test = train_model.predict(list(x_test.to_numpy()))
accuracy_test = sum(p_test == (y_test).to_numpy())/304*100
accuracy_train = sum(p_train == list(y_train.to_numpy()))/710*100
print("accuracy_test:" , accuracy_test, "\n"+"accuracy_train: " , accuracy_train)

accuracy_test: 77.30263157894737 
accuracy_train:  92.95774647887323


In [555]:
s = cross_val_score(model, x_train, y_train , cv = 8)
c = np.mean(s)
print("cross val score: %" , c*100)

cross val score: % 81.26117211440244


In [556]:
m = confusion_matrix(y_test, p_test)
print(m)

[[98 20  5]
 [19 68 10]
 [ 6  9 69]]


# SVM

In [587]:
model = svm.SVC(degree = 5 , kernel="linear" , gamma = "auto" , random_state=3)
train_model = model.fit(x_train, list(y_train.to_numpy()))
p_train = train_model.predict(list(x_train.to_numpy()))
p_test = train_model.predict(list(x_test.to_numpy()))
accuracy_test = sum(p_test == (y_test).to_numpy())/304*100
accuracy_train = sum(p_train == list(y_train.to_numpy()))/710*100
print("accuracy_test:" , accuracy_test, "\n"+"accuracy_train: " , accuracy_train)

accuracy_test: 60.19736842105263 
accuracy_train:  68.30985915492957


In [588]:
s = cross_val_score(model, x_train, y_train , cv = 7)
c = np.mean(s)
print("cross val score: %" , c*100)

cross val score: % 66.74986826413735


In [589]:
m = confusion_matrix(y_test, p_test)
print(m)

[[101  20   2]
 [ 55  29  13]
 [ 11  20  53]]


# RandomForest

In [ ]:
model = RandomForestClassifier(max_depth=20, random_state=3)
train_model = model.fit(x_train, list(y_train.to_numpy()))
p_train = train_model.predict(list(x_train.to_numpy()))
p_test = train_model.predict(list(x_test.to_numpy()))
accuracy_test = sum(p_test == (y_test).to_numpy())/304*100
accuracy_train = sum(p_train == list(y_train.to_numpy()))/710*100
print("accuracy_test:" , accuracy_test, "\n"+"accuracy_train: " , accuracy_train)

In [596]:
s = cross_val_score(model, x_train, y_train , cv = 7)
c = np.mean(s)
print("cross val score: %" , c*100)

cross val score: % 81.83015780569653


In [597]:
m = confusion_matrix(y_test, p_test)
print(m)

[[98 22  3]
 [14 73 10]
 [ 2  8 74]]


In [603]:
model = RandomForestClassifier(max_depth=10, random_state=4)
train_model = model.fit(x_train, list(y_train.to_numpy()))
p_train = train_model.predict(list(x_train.to_numpy()))
p_test = train_model.predict(list(x_test.to_numpy()))
accuracy_test = sum(p_test == (y_test).to_numpy())/304*100
accuracy_train = sum(p_train == list(y_train.to_numpy()))/710*100
print("accuracy_test:" , accuracy_test, "\n"+"accuracy_train: " , accuracy_train)

accuracy_test: 75.98684210526315 
accuracy_train:  90.56338028169014


In [600]:
s = cross_val_score(model, x_train, y_train , cv = 7)
c = np.mean(s)
print("cross val score: %" , c*100)

cross val score: % 81.83015780569653


In [601]:
m = confusion_matrix(y_test, p_test)
print(m)

[[98 22  3]
 [14 73 10]
 [ 2  8 74]]
