In [78]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import random
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier
from sklearn import svm
from sklearn.neighbors import KNeighborsClassifier
from sklearn import tree
from sklearn.decomposition import PCA

In [58]:
data_frame = pd.read_csv("pd_speech_features.csv")
data_frame

Unnamed: 0 Unnamed: 1 Baseline Features Unnamed: 3 Unnamed: 4 Unnamed: 5  \
0           id     gender               PPE        DFA       RPDE  numPulses   
1            0          1           0.85247    0.71826    0.57227        240   
2            0          1           0.76686    0.69481    0.53966        234   
3            0          1           0.85083    0.67604    0.58982        232   
4            1          0           0.41121    0.79672    0.59257        178   
..         ...        ...               ...        ...        ...        ...   
752        250          0           0.80903    0.56355    0.28385        417   
753        250          0           0.16084    0.56499    0.59194        415   
754        251          0           0.88389    0.72335    0.46815        381   
755        251          0           0.83782     0.7489    0.49823        340   
756        251          0           0.81304    0.76471    0.46374        340   

           Unnamed: 6        Unnamed: 7          Unnamed: 8    Unnamed: 9  \
0    numPeriodsPulses  meanPeriodPulses  stdDevPeriodPulses  locPctJitter   
1                 239        0.00806353            8.68E-05       0.00218   
2                 233       0.008258256            7.31E-05       0.00195   
3                 231        0.00833959            6.04E-05       0.00176   
4                 177       0.010857733         0.000182739       0.00419   
..                ...               ...                 ...           ...   
752               416       0.004626942            5.22E-05       0.00064   
753               413       0.004549703         0.000219994       0.00143   
754               380       0.005069271         0.000102654       0.00076   
755               339       0.005679019            5.51E-05       0.00092   
756               339       0.005675776            3.71E-05       0.00078   

     ...               Unnamed: 745               Unnamed: 746  \
0    ...  tqwt_kurtosisValue_dec_28  tqwt_kurtosisValue_dec_29   
1    ...                      1.562                     2.6445   
2    ...                     1.5589                     3.6107   
3    ...                     1.5643                     2.3308   
4    ...                     3.7805                     3.5664   
..   ...                        ...                        ...   
752  ...                     3.0706                      3.019   
753  ...                     1.9704                     1.7451   
754  ...                    51.5607                    44.4641   
755  ...                    19.1607                    12.8312   
756  ...                    62.9927                    21.8152   

                  Unnamed: 747               Unnamed: 748  \
0    tqwt_kurtosisValue_dec_30  tqwt_kurtosisValue_dec_31   
1                       3.8686                     4.2105   
2                      23.5155                    14.1962   
3                       9.4959                    10.7458   
4                       5.2558                    14.0403   
..                         ...                        ...   
752                     3.1212                     2.4921   
753                     1.8277                     2.4976   
754                    26.1586                     6.3076   
755                     8.9434                     2.2044   
756                     9.2457                     4.8555   

                  Unnamed: 749               Unnamed: 750  \
0    tqwt_kurtosisValue_dec_32  tqwt_kurtosisValue_dec_33   
1                       5.1221                     4.4625   
2                      11.0261                     9.5082   
3                      11.0177                     4.8066   
4                       4.2235                     4.6857   
..                         ...                        ...   
752                     3.5844                       3.54   
753                     5.2981                     4.2616   
754                     2.8601             

In [66]:
new_data_frame = data_frame.iloc[:,list(range(1,754))]
new_data_frame

Unnamed: 1 Baseline Features Unnamed: 3 Unnamed: 4 Unnamed: 5  \
0       gender               PPE        DFA       RPDE  numPulses   
1            1           0.85247    0.71826    0.57227        240   
2            1           0.76686    0.69481    0.53966        234   
3            1           0.85083    0.67604    0.58982        232   
4            0           0.41121    0.79672    0.59257        178   
..         ...               ...        ...        ...        ...   
752          0           0.80903    0.56355    0.28385        417   
753          0           0.16084    0.56499    0.59194        415   
754          0           0.88389    0.72335    0.46815        381   
755          0           0.83782     0.7489    0.49823        340   
756          0           0.81304    0.76471    0.46374        340   

           Unnamed: 6        Unnamed: 7          Unnamed: 8    Unnamed: 9  \
0    numPeriodsPulses  meanPeriodPulses  stdDevPeriodPulses  locPctJitter   
1                 239        0.00806353            8.68E-05       0.00218   
2                 233       0.008258256            7.31E-05       0.00195   
3                 231        0.00833959            6.04E-05       0.00176   
4                 177       0.010857733         0.000182739       0.00419   
..                ...               ...                 ...           ...   
752               416       0.004626942            5.22E-05       0.00064   
753               413       0.004549703         0.000219994       0.00143   
754               380       0.005069271         0.000102654       0.00076   
755               339       0.005679019            5.51E-05       0.00092   
756               339       0.005675776            3.71E-05       0.00078   

      Unnamed: 10  ...               Unnamed: 744               Unnamed: 745  \
0    locAbsJitter  ...  tqwt_kurtosisValue_dec_27  tqwt_kurtosisValue_dec_28   
1        1.76E-05  ...                     1.5466                      1.562   
2        1.61E-05  ...                      1.553                     1.5589   
3        1.47E-05  ...                     1.5399                     1.5643   
4        4.55E-05  ...                     6.9761                     3.7805   
..            ...  ...                        ...                        ...   
752      2.97E-06  ...                     3.4394                     3.0706   
753      6.50E-06  ...                    19.6733                     1.9704   
754      3.87E-06  ...                   137.3126                    51.5607   
755      5.24E-06  ...                     5.4425                    19.1607   
756      4.40E-06  ...                    11.1487                    62.9927   

                  Unnamed: 746               Unnamed: 747  \
0    tqwt_kurtosisValue_dec_29  tqwt_kurtosisValue_dec_30   
1                       2.6445                     3.8686   
2                       3.6107                    23.5155   
3                       2.3308                     9.4959   
4                       3.5664                     5.2558   
..                         ...                        ...   
752                      3.019                     3.1212   
753                     1.7451                     1.8277   
754                    44.4641                    26.1586   
755                    12.8312                     8.9434   
756                    21.8152                     9.2457   

                  Unnamed: 748               Unnamed: 749  \
0    tqwt_kurtosisValue_dec_31  tqwt_kurtosisValue_dec_32   
1                       4.2105                     5.1221   
2                      14.1962                    11.0261   
3                      10.7458                    11.0177   
4                      14.0403                     4.2235   
..                         ...                        ...   
752                     2.4921                     3.5844   
753                     2.4976                     5.2981   
754    

In [8]:
test_row =sorted(random.sample(range(1, 756), int(0.3*756)))

In [9]:
train_row = []
for i in range(1,len(data_frame)):
    if i not in test_row:
        train_row.append(i)
train_row = sorted(train_row)

In [94]:
x_train = data_frame.iloc[train_row, list(range(1,754))]
x_train

Unnamed: 1 Baseline Features Unnamed: 3 Unnamed: 4 Unnamed: 5 Unnamed: 6  \
1            1           0.85247    0.71826    0.57227        240        239   
2            1           0.76686    0.69481    0.53966        234        233   
3            1           0.85083    0.67604    0.58982        232        231   
5            0            0.3279    0.79782    0.53028        236        235   
6            0            0.5078    0.78744    0.65451        226        221   
..         ...               ...        ...        ...        ...        ...   
750          1           0.81171    0.79637    0.32824        336        335   
751          0           0.83172    0.57849    0.36017        375        374   
753          0           0.16084    0.56499    0.59194        415        413   
755          0           0.83782     0.7489    0.49823        340        339   
756          0           0.81304    0.76471    0.46374        340        339   

      Unnamed: 7   Unnamed: 8 Unnamed: 9 Unnamed: 10  ... Unnamed: 744  \
1     0.00806353     8.68E-05    0.00218    1.76E-05  ...       1.5466   
2    0.008258256     7.31E-05    0.00195    1.61E-05  ...        1.553   
3     0.00833959     6.04E-05    0.00176    1.47E-05  ...       1.5399   
5    0.008161574  0.002668863    0.00535    4.37E-05  ...       7.8832   
6    0.007631204  0.002696381    0.00783    5.97E-05  ...       6.2888   
..           ...          ...        ...         ...  ...          ...   
750    0.0057387     4.12E-05    0.00079    4.55E-06  ...      11.3087   
751  0.005147376     3.57E-05    0.00088    4.53E-06  ...      10.6174   
753  0.004549703  0.000219994    0.00143    6.50E-06  ...      19.6733   
755  0.005679019     5.51E-05    0.00092    5.24E-06  ...       5.4425   
756  0.005675776     3.71E-05    0.00078    4.40E-06  ...      11.1487   

    Unnamed: 745 Unnamed: 746 Unnamed: 747 Unnamed: 748 Unnamed: 749  \
1          1.562       2.6445       3.8686       4.2105       5.1221   
2         1.5589       3.6107      23.5155      14.1962      11.0261   
3         1.5643       2.3308       9.4959      10.7458      11.0177   
5         6.1727       5.8416       6.0805       5.7621       7.7817   
6         4.8025       5.0734       7.0166       5.9966       5.2065   
..           ...          ...          ...          ...          ...   
750      71.9877      52.2558      26.1383       8.8848       7.5768   
751        2.983       3.3785       3.1691       2.9234       2.5662   
753       1.9704       1.7451       1.8277       2.4976       5.2981   
755      19.1607      12.8312       8.9434       2.2044       1.9496   
756      62.9927      21.8152       9.2457       4.8555       3.0551   

    Unnamed: 750 Unnamed: 751 Unnamed: 752 Unnamed: 753  
1         4.4625       2.6202       3.0004      18.9405  
2         9.5082       6.5245       6.3431       45.178  
3         4.8066       2.9199       3.1495       4.7666  
5        11.6891       8.2103       5.0559       6.1164  
6         7.4246       3.4153       3.5046        3.225  
..           ...          ...          ...          ...  
750      18.2321      28.5223      18.9284      15.5225  
751       2.4621       2.7629       3.0735        5.119  
753       4.2616       6.3042      10.9058       28.417  
755       1.9664       2.6801       2.8332       3.7131  
756       3.0415       4.0116       2.6217       3.1527  

[530 rows x 753 columns]

In [11]:
y_train = data_frame.iloc[train_row, 754]
y_train = y_train.astype(int)
y_train

1      1
2      1
3      1
5      1
6      1
      ..
750    1
751    0
753    0
755    0
756    0
Name: Unnamed: 754, Length: 530, dtype: int32

In [12]:
x_test = data_frame.iloc[test_row ,list(range(1,754))]
x_test

Unnamed: 1 Baseline Features Unnamed: 3 Unnamed: 4 Unnamed: 5 Unnamed: 6  \
4            0           0.41121    0.79672    0.59257        178        177   
8            1           0.83671    0.62079    0.51179        318        317   
10           0           0.85302    0.62247    0.54855        493        492   
15           0           0.80978    0.77992     0.6918        291        290   
19           1           0.78067    0.66085    0.44583        283        282   
..         ...               ...        ...        ...        ...        ...   
737          1           0.71772    0.69237    0.46381        237        236   
739          1           0.80646    0.65101    0.33389        304        303   
741          1           0.82006    0.66421    0.37479        291        290   
752          0           0.80903    0.56355    0.28385        417        416   
754          0           0.88389    0.72335    0.46815        381        380   

      Unnamed: 7   Unnamed: 8 Unnamed: 9 Unnamed: 10  ... Unnamed: 744  \
4    0.010857733  0.000182739    0.00419    4.55E-05  ...       6.9761   
8    0.006073855  0.000135739    0.00282    1.71E-05  ...         1.58   
10   0.003910221     3.99E-05    0.00075    2.93E-06  ...       2.6796   
15   0.006624185  0.002756584    0.00457    3.03E-05  ...       5.2713   
19   0.006824086  0.000138247    0.00177    1.21E-05  ...       1.7356   
..           ...          ...        ...         ...  ...          ...   
737  0.008143903     5.69E-05    0.00189    1.54E-05  ...       1.5343   
739  0.006334744     4.39E-05    0.00117    7.38E-06  ...       1.5611   
741  0.006629164     8.36E-05    0.00154    1.02E-05  ...       1.5892   
752  0.004626942     5.22E-05    0.00064    2.97E-06  ...       3.4394   
754  0.005069271  0.000102654    0.00076    3.87E-06  ...     137.3126   

    Unnamed: 745 Unnamed: 746 Unnamed: 747 Unnamed: 748 Unnamed: 749  \
4         3.7805       3.5664       5.2558      14.0403       4.2235   
8         3.8564      11.8909       7.2891       4.3682       3.6443   
10        1.6796       2.0474       2.8117        3.507       3.2727   
15         5.563       7.1639       3.6436       2.6136       2.7311   
19        2.2674       9.2329       3.3688       4.5787       8.8156   
..           ...          ...          ...          ...          ...   
737       14.382      30.8291      36.9618      41.4248      54.3531   
739     160.3837      78.5401      13.3346        6.197       7.5366   
741      39.3346      53.8215      17.3874      11.8498      11.4329   
752       3.0706        3.019       3.1212       2.4921       3.5844   
754      51.5607      44.4641      26.1586       6.3076       2.8601   

    Unnamed: 750 Unnamed: 751 Unnamed: 752 Unnamed: 753  
4         4.6857        4.846        6.265       4.0603  
8          5.961      11.7552      18.0927       5.0448  
10        3.8415       3.9439       5.8807      38.7211  
15        2.5961       4.8996        14.91      66.2652  
19       18.7743      18.5582      17.0055       4.1109  
..           ...          ...          ...          ...  
737      58.1079      48.6683      38.6414      86.4028  
739       6.5827        6.031       3.8558       3.2026  
741       6.3404       4.1468       3.9736       3.5569  
752         3.54       3.3805       3.2003       6.8671  
754       2.5361       3.5377       3.3545       5.0424  

[226 rows x 753 columns]

In [13]:
y_test =  data_frame.iloc[test_row ,754]
y_test =  y_test.astype(int)
y_test

4      1
8      1
10     1
15     1
19     1
      ..
737    0
739    0
741    0
752    0
754    0
Name: Unnamed: 754, Length: 226, dtype: int32

In [14]:
p_test = [1 for i in range(226)]
p_train = [1 for i in range(530)]
accuracy_test = sum(y_test.to_numpy() == p_test)/226*100
accuracy_train = sum(y_train.to_numpy() == p_train)/530*100
print("accuracy_test:" , accuracy_test, "\n"+"accuracy_train: " , accuracy_train)

accuracy_test: 72.12389380530973 
accuracy_train:  75.66037735849058


# DecisionTree

In [15]:
model = tree.DecisionTreeClassifier(criterion= "entropy", max_depth = 10 ,min_samples_split = 2,min_samples_leaf = 2 , max_features = "log2")
train_model = model.fit(x_train, list(y_train.to_numpy()))
p_train = train_model.predict(list(x_train.to_numpy()))
p_test = train_model.predict(list(x_test.to_numpy()))
accuracy_test = sum(y_test.to_numpy() == p_test)/226*100
accuracy_train = sum(y_train.to_numpy() == p_train)/530*100
print("accuracy_test:" , accuracy_test, "\n"+"accuracy_train: " , accuracy_train)

accuracy_test: 71.23893805309734 
accuracy_train:  97.9245283018868


In [16]:
s = cross_val_score(model, x_train, y_train , cv = 6)
c = np.mean(s)
print("cross val score: %" , c*100)

cross val score: % 72.45914198161388


In [17]:
m = confusion_matrix(y_test, p_test)
print(m)

[[ 33  30]
 [ 35 128]]


In [18]:
model = tree.DecisionTreeClassifier(max_depth = 20 , min_samples_leaf = 2 , max_features = "auto")
train_model = model.fit(x_train, list(y_train.to_numpy()))
p_train = train_model.predict(list(x_train.to_numpy()))
p_test = train_model.predict(list(x_test.to_numpy()))
accuracy_test = sum(y_test.to_numpy() == p_test)/226*100
accuracy_train = sum(y_train.to_numpy() == p_train)/530*100
print("accuracy_test:" , accuracy_test, "\n"+"accuracy_train: " , accuracy_train)

accuracy_test: 78.31858407079646 
accuracy_train:  98.11320754716981


In [19]:
s = cross_val_score(model, x_train, y_train , cv = 5)
c = np.mean(s)
print("cross val score: %" , c*100)

cross val score: % 71.50943396226414


In [20]:
m = confusion_matrix(y_test, p_test)
print(m)

[[ 41  22]
 [ 27 136]]


In [21]:
model = tree.DecisionTreeClassifier(max_depth = 10, min_samples_leaf = 1 , max_features = "sqrt" , min_samples_split = 9 )
train_model = model.fit(x_train, list(y_train.to_numpy()))
p_train = train_model.predict(list(x_train.to_numpy()))
p_test = train_model.predict(list(x_test.to_numpy()))
accuracy_test = sum(y_test.to_numpy() == p_test)/226*100
accuracy_train = sum(y_train.to_numpy() == p_train)/530*100
print("accuracy_test:" , accuracy_test, "\n"+"accuracy_train: " , accuracy_train)

accuracy_test: 75.22123893805309 
accuracy_train:  95.66037735849056


In [22]:
s = cross_val_score(model, x_train, y_train , cv = 5)
c = np.mean(s)
print("cross val score: %" , c*100)

cross val score: % 73.9622641509434


In [23]:
m = confusion_matrix(y_test, p_test)
print(m)

[[ 35  28]
 [ 28 135]]


# KNN

In [60]:
model = KNeighborsClassifier(n_neighbors=20, weights='distance', leaf_size=12 , p = 1)
train_model = model.fit(x_train, list(y_train.to_numpy()))
p_train = train_model.predict(list(x_train.to_numpy()))
p_test = train_model.predict(list(x_test.to_numpy()))
accuracy_test = sum(p_test == (y_test).to_numpy())/226*100
accuracy_train = sum(p_train == list(y_train.to_numpy()))/530*100
print("accuracy_test:" , accuracy_test, "\n"+"accuracy_train: " , accuracy_train)

accuracy_test: 74.33628318584071 
accuracy_train:  98.14814814814815


In [25]:
s = cross_val_score(model, x_train, y_train , cv = 8)
c = np.mean(s)
print("cross val score: %" , c*100)

cross val score: % 73.96257349615558


In [26]:
m = confusion_matrix(y_test, p_test)
print(m)

[[ 17  46]
 [ 12 151]]


In [27]:
model = KNeighborsClassifier(n_neighbors=3)
train_model = model.fit(x_train, list(y_train.to_numpy()))
p_train = train_model.predict(list(x_train.to_numpy()))
p_test = train_model.predict(list(x_test.to_numpy()))
accuracy_test = sum(p_test == (y_test).to_numpy())/226*100
accuracy_train = sum(p_train == list(y_train.to_numpy()))/530*100
print("accuracy_test:" , accuracy_test, "\n"+"accuracy_train: " , accuracy_train)

accuracy_test: 68.58407079646017 
accuracy_train:  84.71698113207547


In [28]:
s = cross_val_score(model, x_train, y_train , cv = 8)
c = np.mean(s)
print("cross val score: %" , c*100)

cross val score: % 72.25237449118048


In [40]:
m = confusion_matrix(y_test, p_test)
print(m)

[[ 21  43]
 [ 19 143]]


# SVM

In [55]:
model = svm.SVC(degree = 5 , kernel="linear" , gamma = "auto" , random_state=3)
train_model = model.fit(x_train, list(y_train.to_numpy()))
p_train = train_model.predict(list(x_train.to_numpy()))
p_test = train_model.predict(list(x_test.to_numpy()))
accuracy_test = sum(p_test == (y_test).to_numpy())/226*100
accuracy_train = sum(p_train == list(y_train.to_numpy()))/530*100
print("accuracy_test:" , accuracy_test, "\n"+"accuracy_train: " , accuracy_train)

accuracy_test: 72.12389380530973 
accuracy_train:  76.22641509433963


In [56]:
s = cross_val_score(model, x_train, y_train , cv = 7)
c = np.mean(s)
print("cross val score: %" , c*100)

cross val score: % 74.90977443609023


In [57]:
m = confusion_matrix(y_test, p_test)
print(m)

[[  0  63]
 [  0 163]]


# Random Forest

In [33]:
model = RandomForestClassifier(max_depth=20, random_state=5)
train_model = model.fit(x_train, list(y_train.to_numpy()))
p_train = train_model.predict(list(x_train.to_numpy()))
p_test = train_model.predict(list(x_test.to_numpy()))
accuracy_test = sum(p_test == (y_test).to_numpy())/226*100
accuracy_train = sum(p_train == list(y_train.to_numpy()))/530*100
print("accuracy_test:" , accuracy_test, "\n"+"accuracy_train: " , accuracy_train)

accuracy_test: 86.72566371681415 
accuracy_train:  98.14814814814815


In [34]:
s = cross_val_score(model, x_train, y_train , cv = 7)
c = np.mean(s)
print("cross val score: %" , c*100)

cross val score: % 83.75187969924814


In [35]:
m = confusion_matrix(y_test, p_test)
print(m)

[[ 39  24]
 [  6 157]]


In [52]:
model = RandomForestClassifier(max_depth=11)
train_model = model.fit(x_train, list(y_train.to_numpy()))
p_train = train_model.predict(list(x_train.to_numpy()))
p_test = train_model.predict(list(x_test.to_numpy()))
accuracy_test = sum(p_test == (y_test).to_numpy())/304*100
accuracy_train = sum(p_train == list(y_train.to_numpy()))/710*100
print("accuracy_test:" , accuracy_test, "\n"+"accuracy_train: " , accuracy_train)

accuracy_test: 64.47368421052632 
accuracy_train:  74.64788732394366


In [53]:
s = cross_val_score(model, x_train, y_train , cv = 7)
c = np.mean(s)
print("cross val score: %" , c*100)

cross val score: % 83.38095238095237


In [54]:
m = confusion_matrix(y_test, p_test)
print(m)

[[ 38  25]
 [  5 158]]
